name: Primary PR Check - Code-coverage

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/unit/**"
      - ".github/workflows/pr-check-primary-codecov.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/unit/**"
      - ".github/workflows/pr-check-primary-codecov.yml"

permissions:
  contents: read

jobs:
  coverage:
    runs-on: hl-sdk-py-lin-md

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

      - name: Install dependencies
        run: |
          uv sync --frozen --all-groups --all-packages --all-extras

      - name: Generate Proto Files
        run: uv run python generate_proto.py

      - name: Run unit tests and generate coverage report
        run: |
          uv run pytest tests/unit \
          --cov=src \
          --cov-report=xml \
          --cov-report=term-missing

      - name: Upload coverage to Codecov
        if: github.repository_owner == 'hiero-ledger'
        uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
